name: 'My Custom Action Workflow'

on:
  push:
    branches:
      - main

jobs:
  my-action-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Run my custom action
      uses: ./ .github/actions/my-action  # Pointing to the local action
      with:
        name: 'GitHub User'  # Input value for 'name'

